// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSF.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CSF.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MustBeEnumerationConstantFormat {
            get {
                return ResourceManager.GetString("MustBeEnumerationConstantFormat", resourceCulture);
            }
        }
        
        internal static string MustBeEnumerationConstantDefaultMessage {
            get {
                return ResourceManager.GetString("MustBeEnumerationConstantDefaultMessage", resourceCulture);
            }
        }
        
        internal static string OnlySupportedForEnumTypesFormat {
            get {
                return ResourceManager.GetString("OnlySupportedForEnumTypesFormat", resourceCulture);
            }
        }
        
        internal static string MustBeDecoratedWithFlagsAttribute {
            get {
                return ResourceManager.GetString("MustBeDecoratedWithFlagsAttribute", resourceCulture);
            }
        }
        
        internal static string TypeCodeMustBeValid {
            get {
                return ResourceManager.GetString("TypeCodeMustBeValid", resourceCulture);
            }
        }
        
        internal static string MustBeChildOfRootFormat {
            get {
                return ResourceManager.GetString("MustBeChildOfRootFormat", resourceCulture);
            }
        }
        
        internal static string CannotCreateRootOfFilesystemFormat {
            get {
                return ResourceManager.GetString("CannotCreateRootOfFilesystemFormat", resourceCulture);
            }
        }
        
        internal static string CountOfGuidNonRandomBytesOutOfRangeFormat {
            get {
                return ResourceManager.GetString("CountOfGuidNonRandomBytesOutOfRangeFormat", resourceCulture);
            }
        }
        
        internal static string CannotFixStackTrace {
            get {
                return ResourceManager.GetString("CannotFixStackTrace", resourceCulture);
            }
        }
        
        internal static string FractionMustSimplifyToInteger {
            get {
                return ResourceManager.GetString("FractionMustSimplifyToInteger", resourceCulture);
            }
        }
        
        internal static string FractionDenominatorCannotBeZero {
            get {
                return ResourceManager.GetString("FractionDenominatorCannotBeZero", resourceCulture);
            }
        }
        
        internal static string InvalidFractionFormat {
            get {
                return ResourceManager.GetString("InvalidFractionFormat", resourceCulture);
            }
        }
        
        internal static string MustBeSixteenBytesInAGuid {
            get {
                return ResourceManager.GetString("MustBeSixteenBytesInAGuid", resourceCulture);
            }
        }
        
        internal static string CannotCreateZeroBasedNegativeAlphabeticReference {
            get {
                return ResourceManager.GetString("CannotCreateZeroBasedNegativeAlphabeticReference", resourceCulture);
            }
        }
        
        internal static string EmptyStringNotPermittedForZeroBasedReferences {
            get {
                return ResourceManager.GetString("EmptyStringNotPermittedForZeroBasedReferences", resourceCulture);
            }
        }
        
        internal static string AlphabeticReferenceMustBeInValidFormat {
            get {
                return ResourceManager.GetString("AlphabeticReferenceMustBeInValidFormat", resourceCulture);
            }
        }
        
        internal static string IntegerValueMustNotBeLessThanZero {
            get {
                return ResourceManager.GetString("IntegerValueMustNotBeLessThanZero", resourceCulture);
            }
        }
        
        internal static string IntegerValueMustNotBeLessThanOneForNonZeroBasedOperations {
            get {
                return ResourceManager.GetString("IntegerValueMustNotBeLessThanOneForNonZeroBasedOperations", resourceCulture);
            }
        }
        
        internal static string CurrentCharacterPositionMustNotBeNegative {
            get {
                return ResourceManager.GetString("CurrentCharacterPositionMustNotBeNegative", resourceCulture);
            }
        }
    }
}
