version: '{branch}-{build}'
image: Visual Studio 2017

init:
    - cmd: git config --global core.autocrlf true
    
install:
    - cmd: git submodule update --init --recursive
    - cmd: dotnet tool install --global dotnet-sonarscanner
    
before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m
    - cmd: dotnet-sonarscanner begin /k:"CSF.PrimesAndFractions" /v:AppVeyor_build_%APPVEYOR_BUILD_NUMBER% /o:craigfowler-github /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%SONARCLOUD_SECRET_KEY% /d:sonar.cs.nunit.reportsPaths=%APPVEYOR_BUILD_FOLDER%\CSF.PrimesAndFractions.Tests\TestResults\TestResults.xml /d:sonar.cs.opencover.reportsPaths=%APPVEYOR_BUILD_FOLDER%\CSF.PrimesAndFractions.Tests\TestResults\coverage.opencover.xml

build_script:
    - cmd: dotnet build

test_script:
    - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=\"json,opencover\" /p:CoverletOutput=\"TestResults/\"  --test-adapter-path:. --logger:\"nunit\"

after_test:
    - cmd: dotnet-sonarscanner end /d:"sonar.login=%SONARCLOUD_SECRET_KEY%"
