#!/bin/bash

BUILD_LOCATION=`dirname $0`
SOLUTION_ROOT="$BUILD_LOCATION/.."
configuration_name="${1:-Debug}"

cd "$SOLUTION_ROOT"

git clean -fdx

xbuild "/property:Configuration=${configuration_name}"
